name: Deploy Package

on:
  push:
    tags:
      - 'v*'

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  deploy:
    name: Deploy Package
    runs-on: docker
    container: node:24
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Cache pnpm store
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install node packages
        run: pnpm install --store ${{ env.PNPM_CACHE_FOLDER }}

      - name: set npm config
        run: |
          env
          pnpm config set @richardnbanks:registry https://code.richardbanks.dev/api/packages/${{github.REPOSITORY_OWNER}}/npm/
          pnpm config set -- '//code.richardbanks.dev/api/packages/${{github.REPOSITORY_OWNER}}/npm/:_authToken' "${{secrets.PACKAGE_TOKEN}}"

      - name: Deploy Package
        run: pnpm publish