name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: docker
    container: node:24
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install node packages
        run: npm ci

      - name: Publish package to npmjs.org
        run: npm publish
