name: Deploy Package

on:
  push:
    branches:
      - 'main'

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  deploy:
    name: Deploy Package
    runs-on: docker
    container: node:24-alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: set npm config
        run: |
          env
          pnpm config set @forgejo:registry ${{github.SERVER_URL}}/api/packages/${{github.REPOSITORY_OWNER}}/npm/
          pnpm config set -- '//code.richardbanks.dev/api/packages/${{github.REPOSITORY_OWNER}}/npm/:_authToken' "${{secrets.PACKAGE_TOKEN}}"
          pnpm config list

      - name: Cache pnpm store
        uses: actions/cache@v5
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install node packages
        run: pnpm install --store ${{ env.PNPM_CACHE_FOLDER }}

      - name: Deploy Package
        run: pnpm publish --tag next --scope=@forgejo